name: StreamLine-Helper
version: ${project.version}
main: net.plasmere.streamlinehelper.StreamLineHelper
authors: [ Nitrate ]
description: A plugin to help with the StreamLine Bungeecord plugin!
website: https://store.plasmere.net
softdepend:
  - CMI
  - Essentials
  - PlaceholderAPI

commands:
  streamdebug:
    permission: "streamline.command.streamdebug"
    aliases:
      - "sdebug"
      - "strd"
    description: "Enables / disabled debug for this plugin."
  streamscript:
    permission: "streamline.command.streamscript"
    aliases:
      - "msgscript"
    description: "Sends a script plugin message to Bungeecord / Velocity."